- name: AMI Creation
  hosts: ami
  become: yes
  become_user: root
  tasks:
    - name: ensure machine is up to date
      yum:
        name: '*'
        state: latest
    - name: ensure docker is installed
      yum:
        name: docker
        state: latest
    - name: ensure docker is running
      service:
        name: docker
        enabled: true
        state: started
    - name: ensure ec2-user has the docker group
      user:
        name: ec2-user
        group: docker
        